#
#
#services:
#  postgres:
#    container_name: postgres_container
#    image: postgres:16
#    restart: unless-stopped
#    environment:
#      POSTGRES_USER: postges
#      POSTGRES_PASSWORD: pass
#    ports:
#      - "5432:5433"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin_container
#    restart: unless-stopped
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - postgres
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#
#volumes:
#  postgres_data:
#  pgadmin_data:
