build:
  id: 101
  version: 1.2.3
  name: "Native-Dev-Production-Build"
  type: "native-Development Build"
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    
